# Project identification
sonar.projectKey=timo-jakob_atlassian-cloud-backup
sonar.organization=timo-jakob-github

# Project name and version
sonar.projectName=Atlassian Cloud Backup
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src
sonar.tests=tests

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Python-specific configuration
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
